package main

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/extism/go-pdk"
)

// InferenceRequest defines the JSON payload received from Pollen
type InferenceRequest struct {
	Prompt      string  `json:"prompt"`
	MaxTokens   int     `json:"max_tokens"`
	Temperature float64 `json:"temperature"`
}

// InferenceResponse defines the JSON payload streamed back to Pollen
type InferenceResponse struct {
	Text  string `json:"text"`
	Error string `json:"error,omitempty"`
}

//export run_inference
func run_inference() int32 {
	// 1. Read input payload from Pollen host
	input := pdk.Input()

	var req InferenceRequest
	if err := json.Unmarshal(input, &req); err != nil {
		resp := InferenceResponse{Error: "Failed to parse inference request: " + err.Error()}
		out, _ := json.Marshal(resp)
		pdk.Output(out)
		return 1 // Error code
	}

	// 2. Initialize the WASM LLM Engine
	// In a real WASM/WASI environment, this would initialize the llama-cpp-wasm bindings.
	// Since we are running inside the Pollen WASM sandbox, we execute the inference loop here.
	pdk.Log(pdk.LogInfo, fmt.Sprintf("Starting inference for prompt: %s...", req.Prompt[:min(10, len(req.Prompt))]))

	// Mocking the engine execution for the wrapper design
	generatedText := executeLlamaCppWasm(req.Prompt, req.MaxTokens, req.Temperature)

	// 3. Output the result back to Pollen host
	resp := InferenceResponse{Text: generatedText}
	out, _ := json.Marshal(resp)
	pdk.Output(out)

	return 0 // Success code
}

// executeLlamaCppWasm represents the bridge to the C++ compiled WASM engine
func executeLlamaCppWasm(prompt string, maxTokens int, temp float64) string {
	// Here we would call the exported functions from the llama.cpp WASM module
	// For demonstration, we simulate streaming output

	// Simulate "streaming" back to the host via Pollen's log/emit functions if needed,
	// or returning the complete string when done.
	return strings.ToUpper(prompt) + " (Generated by Pollen WASM Compute)"
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func main() {
	// The main function is required for TinyGo/Extism to compile to WASM,
	// but the exported functions (like run_inference) are what Pollen calls.
}
